name: Build and Deploy Docker Image to Docker Hub and Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows you to manually trigger the workflow from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log into Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/weather_app:latest .

      # Run tests in the Docker container (for example, using pytest)
      - name: Run tests
        run: |
          docker run ${{ secrets.DOCKER_USERNAME }}/weather_app:latest pytest tests/

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/weather_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deployment runs after the build job

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Azure using GitHub Secrets
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          
      # Deploy to Azure Web App using Docker image
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: weather-app-devops-DE23
          images: ${{ secrets.DOCKER_USERNAME }}/weather_app:latest
