name: test

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."


    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          mousavin0/weather_app:latest
        secrets: |
          OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:

      # Log in to Azure using GitHub Secrets
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


          
      # Deploy to Azure Web App using Docker image
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: weather-app-devops-DE23
          images: mousavin0/weather_app:latest
