name: test

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo ${{ secrets.DOCKER_USERNAME }}

