name: Run Tests

on:
  workflow_dispatch:
    inputs:
      log_errors:
        description: 'Set to true to log errors if tests fail'
        required: true
        default: 'true'

jobs:
  # Run unit and integration tests in one job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        id: unit_tests
        run: |
          echo "Running unit tests..."
          pytest tests/unit_test.py
          echo "::set-output name=unit_tests_outcome::${{ steps.unit_tests.outcome }}" # Capture outcome explicitly
        continue-on-error: false  # Fail the job if this step fails

      - name: Run integration tests
        id: integration_tests
        run: |
          echo "Running integration tests..."
          pytest tests/integration_test.py
          echo "::set-output name=integration_tests_outcome::${{ steps.integration_tests.outcome }}" # Capture outcome explicitly
        continue-on-error: false  # Fail the job if this step fails

  # Logging job that will only run if the test job fails
  log_errors:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ failure() && github.event.inputs.log_errors == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Capture error logs from unit tests
        run: echo "Unit tests failed. Check the logs for more details." >> error_log.txt

      - name: Capture error logs from integration tests
        run: echo "Integration tests failed. Check the logs for more details." >> error_log.txt

      - name: Upload error log if tests failed
        uses: actions/upload-artifact@v4
        with:
          name: error_log
          path: error_log.txt
    
      - name: Debug Conclusion
        run: echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"

